Performer= 'Ed Sheeran'
Title=     "Hearts Don't Break Around Here"
Album=     'Divide'
Year=      2017

Performer= 'Queen'
Title=     'Bohemian Rhapsody'
Album=     'A Night at the Opera'
Year=      1975
# class definition
'''class Song:
   def __...___(self,...,...,...,...):
      ...
      ...
      ...
      ...
   def __str.............
      ...
      ...
      ...
'''
# object creation
song1 = ...
song2 = ...

## object usage
print(song1)
...